name: Basil & Fabian - A Wizard & His Man
markdown: redcarpet
highlighter: true
exclude: [ Cakefile, public ]
url: http://blog.jamisbuck.org
description: |
  Follow the wizard Basil and his sarcastic sidekick Fabian as they discover
  and explain algorithm after algorithm. Each chapter of their adventures is
  lovingly hand-crafted and illustrated by millions of tiny cells, miraculously
  acting in focused unison.

redcarpet:
  extensions: [ smart ]

uuid: 020d5ac0-0efa-11e4-9191-0800200c9a66
